/* Generated by Yosys 0.39 (git sha1 00338082b, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module flip(clk, en, d, q);
  wire _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  input en;
  wire en;
  output q;
  wire q;
  sky130_fd_sc_hd__mux2_4 _1_ (
    .A0(q),
    .A1(d),
    .S(en),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 \q$_DFFE_PP_  (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule